### ISSUE TITLE
Viewer renders only partial warped maps

### ISSUE THREAD

**Issue by julienperret** [allmaps/allmaps#15] opened 2023-02-14 15:12 UTC
I have the same issue on the main and develop branches.

![image](https://user-images.githubusercontent.com/6437740/218778175-435808c2-6825-4036-8409-4dfde49a5992.png)

**Comment by bertspaan** [comment] 2023-02-15 08:02
I am aware of a few rendering issues, I'm currently working on fixing those.

What browser + OS are you using?

**Comment by julienperret** [comment] 2023-02-15 12:15
I'm on Ubuntu. I have the same issue on Firefox & Chrome.
Do you think a dockerized version might help (if just for reproducibility)?

**Comment by bertspaan** [comment] 2023-02-15 12:25
Does the rest of the warped map appear when you move the map just a little after it has been in the screenshot's state for a while? Does this happen for every Georeference Annotation? Are there errors in the browser's console?

**Comment by julienperret** [comment] 2023-02-15 12:51
The visible part of the warped map moves as I move.
There is no error in the console (just a few WebGL warnings).
![image](https://user-images.githubusercontent.com/6437740/219031788-b746bf41-33fa-40bf-9f85-a3317eefbb08.png)

**Comment by bertspaan** [comment] 2023-02-16 14:01
The problem is probably caused by a bug in the [WebGL2WarpedMap](https://github.com/allmaps/allmaps/blob/develop/packages/render/src/WebGL2WarpedMap.ts) class in @allmaps/render. It seems something goes wrong during loading IIIF tiles and then turning them into WebGL textures. I'm working on the render module the coming time, but help is welcome!

**Comment by bertspaan** [comment] 2023-02-16 15:53
Just deployed a new version on https://dev.viewer.allmaps.org/. Seems to be working much better. Can you try it?

**Comment by julienperret** [comment] 2023-02-17 13:23
This works perfectly!
I'll try to test the latest version of the develop branch.

**Comment by bertspaan** [comment] 2023-02-17 13:36
Still a few issues, I'll keep working on fixing those the next days.

**Comment by garrettdashnelson** [comment] 2023-02-17 17:07
I was noticing this exact same error on Wednesday of this week, and it now seems to be corrected for me in the latest version of dev.viewer.

**Comment by julienperret** [comment] 2023-02-21 11:12
I guess we can close this issue?

**Comment by bertspaan** [comment] 2023-02-21 11:29
Almost! Sometimes IIIF tiles are loaded but the warped map is not re-rendered. Working on that this week, I'll close this issue when it's done.

**Comment by bertspaan** [comment] 2023-02-23 12:45
I just pushed a new version of @allmaps/render and https://dev.viewer.allmaps.org. I did not yet solve the tile re-rendering issue mentioned above, but I did fix the problem that caused the warped map to shake when zoomed in very far.

**Closed** 2023-10-25 18:39 UTC
Labels: viewer
